### ISSUE TITLE
Create: Deploy Environment

### ISSUE THREAD

**Issue by m-tsuru** [ichidaisai/2024.ichidaisai.com#17]
Create Deploy Environment

Deploy `main` to deploy service

- [x] ~~Create appropriate account of deploy service~~
- [x] Decide deploy service 
  - Cloudflare Pages 
  - ~~Vercel~~
  - ~~FIrebase~~
- [x] Get `ichidaisai.com` and `2024.ichidasai.com`
  - [x] Contact `ichidaisai.com` Administrator
  - [x] Set CNAME

**Comment by m-tsuru** [comment]
VitePress を利用します．
Branch: `vitepress-feature`

**Comment by m-tsuru** [comment]
何を言っているんだ　使わなくてもできるだろ

**Comment by m-tsuru** [comment]
既に市大システム局のアカウントを Cloudflare が持っていたため，Cloudflare Pages にデプロイすることにした．

## デプロイ 
- `main` ブランチの自動デプロイを有効化
- カスタムドメインは以下の通り
  - `2024.ichidaisai.com`
  - `ichidaisai.com`

## TODO
[ ] プレビュー環境も作成し，カスタムドメインに紐づける

**Comment by m-tsuru** [comment]
完了したのでクローズ
